### ISSUE TITLE
ddt clean always deletes the current libraries rlib

### ISSUE THREAD

**Issue by MisterEggnog** [dudykr/ddt#8]
I was writing some basic tests for `ddt clean`. In doing so I also found a bug where it will always delete the current library's rlib, even in situations where the dependencies have not been changed.

I have included a test for this in #9.

**Comment by kdy1** [comment]
I'm sorry, but I'm closing this as I decided to drop `ddt clean`. Maybe I add similar feature in the future, but for now, I don't want to use very good name for such a narrow task.
